_DEBUG = False

# actual size of the window
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 45

LVL0_MAP_WIDTH = 1
LVL0_MAP_HEIGHT = 1
 
LIMIT_FPS = 15  # frames-per-second maximum
PROFILE = True

PLAYER_MAX_SIGHT = 31
RENDER_RADIUS_CIRCLE = PLAYER_MAX_SIGHT + 5